### ISSUE TITLE
Not all files are installed on text install

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-utils#1]
_From @DmitryPostolov on August 10, 2016 3:30_

Not all files are installed on text install. With Graphic installer all OK, but with text installer not all files are installed and after reboot -> problem with Graphic mode after text install. TrueOS Image from 2016-08-08. NUC DN2820FYKH. CPU Intel N2830.

_Copied from original issue: trueos/trueos-core#26_

**Comment by kmoore134** [comment]
_From @DmitryPostolov on August 16, 2016 14:40_

I am try again with TrueOS Image from 2016-08-14 and this problem with text installer is not solved. After text installation some applications are absent, for example: qterminal and browser. And problem with Graphic mode after text install not solved. There are no problems with absent applications and Graphic mode after Graphic Installation. Intel NUC DN2820FYKH. CPU N2830 HD Graphics.

![aftertextinstall](https://cloud.githubusercontent.com/assets/20837310/17702881/8aeaf610-63f1-11e6-8c35-14d15d9cdc3f.jpg)

**Comment by kmoore134** [comment]
This fixes the missing pkgs. The graphics issue is most likely problem with i915kms driver. It should be reported here:

https://github.com/FreeBSDDesktop/freebsd-base-graphics

**Comment by DmitryPostolov** [comment]
Kris, but if "The graphics issue is most likely problem with i915kms driver" then why all OK with Graphics after GUI installation?

**Comment by kmoore134** [comment]
Ok, i mis-understood your issue. If you do a graphical install, it does the /etc/X11/xorg.conf generation automatically, which gets copied to installed system. If you do text-install it does not, which means you have to create that file yourself post-install. I'll look at our initial boot code to see if we can resolve that.

**Comment by DmitryPostolov** [comment]
In image from 31-aug all OK in text install and after it Graphic mode OK, but for Desktop in file /etc/rc.conf the string: "kldload_i915kms="i915kms" is missing and booting screen not for HD resolution for lines/columns before PCDM starts.
